DTOs:
  - name: "SellerEntity"
    params:
      id: "int"
      company_id: "int"
      name: "string"
      description: "string"
      enabled: "bool"
      created_at: "DateTime"
      updated_at: "DateTime"
